# 测试随机数



In [1]:
from gym.envs.registration import registry


In [3]:
import gym


gym.__version__

'0.21.0'

In [1]:
import numpy as np


In [21]:
if np.random.binomial(1, 0.05):
    print(1)
else:
    print(0)

0


In [1]:
import torch

d:\SF\Anaconda\envs\rlenv\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [3]:
a = torch.ones((32, 6))

In [45]:
b = torch.zeros((32, 1), dtype=int)

In [46]:
a.index_select(0, b).shape

IndexError: index_select(): Index is supposed to be a vector

In [27]:
b = torch.LongTensor(b)

In [28]:
a.index_select(0, b).shape

torch.Size([32, 6])

In [23]:
x = torch.randn(3, 4)

In [29]:
x

tensor([[-1.8833,  1.3188, -1.4585, -1.9353],
        [-1.0713, -1.0944,  1.4170, -0.0829],
        [-1.5425,  0.6221, -0.3379, -1.1149]])

In [34]:
x[:, 1]

tensor([ 1.3188, -1.0944,  0.6221])

In [35]:
import numpy as np


In [37]:
x = np.random.rand(3, 4)

In [43]:
x[list(range(3)), (1, 2, 3)]

array([0.38373749, 0.26202623, 0.34415568])

In [44]:
x[:,(1, 2, 3)]

array([[0.38373749, 0.71326132, 0.01444108],
       [0.18047015, 0.26202623, 0.43309366],
       [0.7817636 , 0.54691312, 0.34415568]])